# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment mappings, see https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

# Environment Properties
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
neo_version=21.11.45
neo_version_range=[21.11.0-beta,)
loader_version_range=[5,)

# Dependencies
geckolib_version=5.4.5
geckolib_version_range=[5.4,)

# Mod Properties
mod_id=amogusmod
mod_name=AMOGUS
mod_license=CC-BY-NC-SA-4.0
mod_version=1.3.0
mod_group_id=net.klode.amogusmod
mod_authors=Klode
mod_description=A very SUS mod
